register_configuration(static_native)
register_configuration(dynamic_native)
register_configuration(arm)
register_configuration(i386)
register_configuration(mips)
register_configuration(mipsel)
register_configuration(s390x)
register_configuration(x86_64)
register_configuration(aarch64)

set(NATIVE_CONFIGURATIONS "static_native;dynamic_native")
